config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  
  get 'signup'  => 'users#new' 
  resources :users
  
  get 'users' => 'users#index'
  get 'users/:id' => 'users#show'

  get 'create-house' => 'houses#new'
  get '/houses' => 'houses#index'
  resources :houses
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'
  
  get '/unreal' => 'webplayers#index'
  
  post '/' => 'sessions#create'
  
  get 'dashboard' => 'pages#dashboard'
  
  get 'index' => 'pages#index'
  get '/my-houses' => 'builder#houses'
  get '/my-customers' => 'builder#customers'
  get '/my-customers/:id' => 'builder#customer_info'
  get '/my-options' => 'builder#options'
  
  
  resources :options
  get 'all-users' => 'admin#users'
  get 'all-houses' => 'admin#houses'
  get 'all-options' => 'admin#options'
  
  get 'highscore' => 'unity#highscore'
  get 'highscoreUpdate' => 'unity#highscoreUpdate'
  get 'optionsJSON' => 'unity#optionsJSON'
  
  get 'houseName' => 'unity#houseName'
  get 'houseNameUpdate' => 'unity#houseNameUpdate'
  
  get 'game' => 'pages#game'
  get 'game/index.html' => 'pages#game'
  
  get 'username' => 'unity#username'
  
  get 'gameStarter/:id' => 'unity#gameStarter'
  get 'gameTester' => 'unity#gameTester'
  post 'updateChoices' => 'unity#updateChoices'
  
  get 'gameData' => 'unity#gameData'
  
  get 'communities' => 'builder#communities'
  post 'communities' => 'builder#createCommunity'
  get 'loginStats' => 'pages#loginStats'
  
  

end

app/controllers/builder_controller.rb
class BuilderController < ApplicationController
    before_action :require_builder
    
    def houses
        @houses = current_user.houses
        @homes = current_user.houses
        @ready = @homes.where(status: "ready")
        
        @pending = @homes.where(status: "pending")
        
    end
    
    
    def customers
        @user = current_user
        @customers = @user.customers
        @communities = @user.communities
        
        if params[:community]
           @community = Community.find(params[:community])
           
           @peeps = Array.new
           
           @customers.each do |customer|
              if customer.assigned_house && customer.assigned_house.community == @community
                 @peeps << customer
              end
           end
           
            @customers = @peeps
            
        end
    end
    
    
    def customer_info
        @user = current_user
        
        @customer = current_user.customers.find_by(id: params[:id])
        @houses = @user.houses
        
        @house = "none" #House.find(params[:id])
        @house_options = @houses.map{|h| [ h.name, h.id ] }
        
        @house_options.unshift( ['none', nil]);
        
        @current = @customer.assigned_house.id if @customer.assigned_house
        
        
    end
    
    
    def options
        @options = Option.all
        @categorys = @options.collect { |o| o.category }.uniq
        
        if params[:category]
            @options = Option.where(category: params[:category])
        end
    end
    
    
    def communities
       @user = current_user
       @communities = @user.communities
       
       if @selected = params[:id]
           @community = @user.communities.find(@selected)
           @houses = @user.communities.find(@selected).houses
       end
    end
    
    
    def createCommunity
        @community = Community.new(community_params)
        
        current_user.communities << @community
        
        
        @community.save
        
        redirect_to my_customers_path
    end
    
    
    
    private
    def community_params
        params.require(:community).permit(:name) 
    end
end

app/helpers/builder_helper.rb
module BuilderHelper
end

app/views/builder/_houseTiles.html.erb
<div class="row">
    <% houses.each do |h| %>
        <a href="<%= house_path(h) %>">
          <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
              <div class="house-pic" style="background-image: url(<%= h.picture %>)"></div>
              
              <div class="caption">
                <h3><%= h.name %></h3>
              </div>
            </div>
          </div>
        </a>
    <% end %>
</div>

app/views/builder/_users_table2.html.erb
<table class="table"> 
    <br>
    <thead> 
        <tr>
            <th>#</th> <th>Name</th> <th>Email</th> <th>Assigned House</th><th>Role</th>
        </tr> 
    </thead> 
    <tbody>
        <% @row = 1 %>
        <% users.each do |u| %>
            
            <tr>
                <th scope="row"><%= @row %></th>
                <td><%= u.first_name + " " + u.last_name %></td>
                <td><%= u.email %></td>'
                <td><%= u.assigned_house %></td>
                <td><%= u.role %></td>
                
                <td>
                    <%= link_to u do %>
                        <button type="button" class="btn btn-primary">View</button>
                    <% end %>
                </td>
                
                <td>
                    <%= link_to edit_user_path(u.id) do %>
                        <button type="button" class="btn btn-info">Edit</button>
                    <% end %>
                </td>
                
                
            </tr>
            <% @row += 1 %>
            
        <% end %>
        
    </tbody> 
</table>

app/views/builder/communities.html.erb
<h2>My Communities</h2>
<hr>
<br>

<div class="row">
    <div class="col-md-2 sidebar">
        <ul class="nav nav-pills nav-stacked">
        <% @communities.each do |c| %>
            <li role="presentation" <% if params[:id] == c.id.to_s %> class="active" <% end %>>
                <a href="?id=<%= c.id %>"><%= c.name %></a>
            </li>
        <% end %>
        </ul>
        
    </div>
    
    
    
    <div class="col-md-8 col-md-offset-1">
        <table class="table">
            <thead>
                <tr>
                    <th>House Name</th>
                    <th>Address</th>
                    
                </tr>
            </thead>
            
            <% if @selected %>
            <tbody>
                <% @houses.each do |house| %>
                    <tr>
                        <td><%= link_to house.name, house %></td>
                        <td><%= house.address %></td>
                    </tr>
                <% end %>
            </tbody>
            <% end %>
            
        </table>
    </div>
</div>
<hr>
<br>
<h3>New Community</h3>
<%= form_for(@com = Community.new) do |f| %>
    
    <label>Community Name</label>
    <div class="form-group">
        <%= f.text_field :name, :placeholder => "Community name", :class => "form-control" %>
    </div>
    
    <%= f.submit "Add ", class: "btn btn-primary" %>
    
<% end %>

app/views/builder/customer_info.html.erb
<h2>Customer Details</h2>
<hr>

<h4>Name: </h4>
<h2><%= @customer.first_name + " " + @customer.last_name %></h2>


<br>
<hr>
<h4>House: </h4>
<h2>
<% if @customer.assigned_house %>
    <%= @customer.assigned_house.name %>
<% else %>
    They have no house
<% end %>
</h2>

  <% if false %>
  <div class="dropdown">
    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
      Dropdown
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
      <li><a href="#">house_name</a></li>
      <li><a href="#">house_name</a></li>
      <li><a href="#">house_name</a></li>
      <li role="separator" class="divider"></li>
      <li><a href="#">house_name</a></li>
    </ul>
  </div>
  <% end %>
  
  <%= form_for(@customer) do |f| %>
    <%= f.select(:assigned_house, @house_options, :selected => @current) %>
    <%= f.submit "Update House", class: "btn btn-primary btn-sm" %>
  <% end %>
<hr>

app/views/builder/customers.html.erb
<h2>My Customers</h2>
<hr>

<div class="row">
  <div class="col-md-2 sidebar">
    <ul class="nav nav-pills nav-stacked">
            <li role="presentation" <% if params[:community] == nil %> class="active" <% end %> >
                <a href="?"><b>All Customers</b></a>
            </li>
            <br>
            <% @communities.each do |c| %>
                <li role="presentation" <% if params[:community] == c.id.to_s %> class="active" <% end %>>
                    <a href="?community=<%= c.id %>">
                        <%= c.name %>
                    </a>
                </li>
            <% end %>
        </ul>
        <br>
        <%= link_to communities_path do %>
          <button type="button" class="btn btn-info">Add Community</button>
        <% end %>
        <hr>
        <%= link_to new_user_path do %>
          <button type="button" class="btn btn-success">Add Customer</button>
        <% end %>
        
  </div>
  
  <div class="col-md-10">
    
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Login Count</th>
          <th>Assigned House</th>
          <th></th>
        </tr>
      </thead>
      
      <tbody>
        <% @customers.each do |c| %>
          <tr>
            <td><%= c.first_name + " " + c.last_name %></td>
            <td><%= c.email %></td>
            
            <td><%= c.loginCount %></td>
            
            <td>
              <% if c.assigned_house %>
                <a href="<%= house_path(c.assigned_house) %>"><%= c.assigned_house.name %></a>
              <% else %>
                
              <% end %>
            </td>
            
            <td>
              <%= link_to "/my-customers/" + c.id.to_s do %>
                  <button type="button" class="btn btn-primary">Customer Details</button>
              <% end %>
            </td>
            
          </tr>
        <% end %>
      </tbody>
    </table>
    
  </div>
</div>

app/views/builder/houses.html.erb
<h2>My Houses  
<%= link_to new_house_path do %>
    <button type="button" class="btn btn-primary btn-lg">Add New Home</button>
  <% end %></h2>
  
  
<hr>
  <%= render partial: "houseTiles", locals: {houses: @ready} %>
<br>


<h2>Pending Houses</h2>
<hr>
  <%= render partial: "houseTiles", locals: {houses: @pending} %>
<hr>


<p>
  <%= link_to new_house_path do %>
    <button type="button" class="btn btn-primary btn-lg">Add New Home</button>
  <% end %>
</p>

app/views/builder/options.html.erb
<br><br>
<ul class="nav nav-tabs nav-justified">
    <li role="presentation" <% if params[:q] == nil %> class="active" <% end %>>
        <a href="?"><strong>My Options</strong></a>
    </li>
    
    <li role="presentation" <% if params[:q] == "all" %> class="active" <% end %>>
        <a href="?q=all"><strong>All Options</strong></a>
    </li>
</ul>
<hr>
<br>
<% if true %>
<div class="row">

    <div class="col-md-2 sidebar">
        <ul class="nav nav-pills nav-stacked">
            <li role="presentation" <% if params[:category] == nil %> class="active" <% end %> >
                <a href="?">All Options</a>
            </li>
            <hr>
            <% @categorys.each do |c| %>
                <li role="presentation" <% if params[:category] == c %> class="active" <% end %>>
                    <a href="?category=<%= c %>">
                        <%= c %>
                    </a>
                </li>
            <% end %>
        </ul>
    </div>
    
    
    <div class="col-md-10 main">
        <%= render "shared/options/builder_table" %>
    </div>
</div>
<% end %>