config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  
  get 'signup'  => 'users#new' 
  resources :users
  
  get 'users' => 'users#index'
  get 'users/:id' => 'users#show'

  get 'create-house' => 'houses#new'
  get '/houses' => 'houses#index'
  resources :houses
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'
  
  get '/unreal' => 'webplayers#index'
  
  post '/' => 'sessions#create'
  
  get 'dashboard' => 'pages#dashboard'
  
  get 'index' => 'pages#index'
  get '/my-houses' => 'builder#houses'
  get '/my-customers' => 'builder#customers'
  get '/my-customers/:id' => 'builder#customer_info'
  get '/my-options' => 'builder#options'
  
  
  resources :options
  get 'all-users' => 'admin#users'
  get 'all-houses' => 'admin#houses'
  get 'all-options' => 'admin#options'
  
  get 'highscore' => 'unity#highscore'
  get 'highscoreUpdate' => 'unity#highscoreUpdate'
  get 'optionsJSON' => 'unity#optionsJSON'
  
  get 'houseName' => 'unity#houseName'
  get 'houseNameUpdate' => 'unity#houseNameUpdate'
  
  get 'game' => 'pages#game'
  get 'game/index.html' => 'pages#game'
  
  get 'username' => 'unity#username'
  
  get 'gameStarter/:id' => 'unity#gameStarter'
  get 'gameTester' => 'unity#gameTester'
  post 'updateChoices' => 'unity#updateChoices'
  
  get 'gameData' => 'unity#gameData'
  
  get 'communities' => 'builder#communities'
  post 'communities' => 'builder#createCommunity'
  get 'loginStats' => 'pages#loginStats'
  
  

end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
    
    before_action :require_user
  
    
    def index
        @houses = House.all
    end
    
    def show
        @house = House.find(params[:id])
        @options = @house.options
        
        
        
    end
    
    def edit
        @house = House.find(params[:id])
        @options = Option.all
        
        
        #if current_user.builder?
           
           #@house.users needs to be @house.builder
           @communities = @house.users.first.communities
           
           @communitiesList = @communities.map{|c| [ c.name, c.id ] }
           
           @communitiesList.unshift( ['none', nil] );
           
           @current = nil
           
           @current = @house.community.id if @house.community
            
           
        #end
    end
    
    def update
        @house = House.find(params[:id])
        
        puts ">>>>>>>> UPDATING HOUSE <<<<<<<<<"
        
        if params[:op_hash]
            @house.options.clear
            params[:op_hash].each do |k, v|
               @op = Option.find(k)
               @house.options << @op
            end
        end
        
        if params[:house][:community]
            if params[:house][:community] == ""
                @house.community_house_link.destroy
            else
                @house.community = Community.find(params[:house][:community])
            end
            @house.save
        end
        
        if @house.update(house_params)
            redirect_to @house
        else
            render 'edit'
        end
    end
    
    def new
        @house = House.new
    end
    
    def create
        @house = House.new(house_params)
        
        if current_user.builder?
            @house.status = "pending"
            current_user.houses << @house
        end
        
        if @house.save
            redirect_to @house
        else
            redirect_to "#"
        end
    end
    
    def destroy
        @house = House.find(params[:id])
        @house.destroy
        
        if current_user.admin?
            redirect_to '/houses'
            
        end 
        
        if current_user.builder?
            redirect_to '/my-houses'
            
        end
    end
    
    
    private
    def house_params
        params.require(:house).permit(:name, :address, :image, :picture, :file, :status, :score, :meta)
    end
    
    
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/houses/edit.html.erb
    <h2>Edit House</h2>
    
    
    <%= form_for(@house, html: { multipart: true }) do |f| %>
    
      <div class="form-group" >
          <%= label_tag(:name, "House Name") %>
          <%= f.text_field :name, :class => "form-control" %>
      </div>
      
      <div class="form-group" >
          <%= label_tag(:address, "Adress") %>
          <%= f.text_field :address, :class => "form-control" %>
      </div>
      
      <% if current_user.admin? %>
      <div class="form-group" >
          <%= label_tag(:status, "Status") %>
          <%= f.text_field :status,  :class => "form-control" %>
      </div>
      <% end %>
      
      <br>
      Image
      <%= f.file_field :picture %>
      <br>
      3D File
      <%= f.file_field :file %>
      <br>
      Meta File
      <%= f.file_field :meta %>
      <br>
      
      <hr>
      <h4>Community</h4>
      <%= f.select :community, @communitiesList, :selected => @current %>
      
      
      
      
      
      <br>
      <hr>
      <h4>Options</h4>
      
      
      <% @options.each do |o| %>
        
        <%= check_box_tag("op_hash["+o.id.to_s+"]") %>
        <%=  o.name %>
        <br>
        
      <% end %>
      
      
      <br><br>
      <%= f.submit "Update", class: "btn btn-submit" %>
    <% end %>
    <br>
    <br>
      <br>
    

app/views/houses/index.html.erb
<h2>All Houses</h2>
<hr>

<%= render "shared/house_tiles" %>

<hr>
<p>
  <%= link_to new_house_path do %>
    <button type="button" class="btn btn-primary btn-lg">Add New Home</button>
  <% end %>
</p>

app/views/houses/new.html.erb
<h2>New House</h2>
<hr>

<%= form_for(@house, html: { multipart: true }) do |f| %>

    <div class="form-group">
        <%= f.text_field :name, :placeholder => "House name", :class => "form-control" %>
    </div>
    
    <div class="form-group">
        <%= f.text_area :address, :placeholder => "House address", :class => "form-control" %>
    </div>
    
    <% if current_user.admin? %>
     <div class="form-group">
        <%= f.text_field :status, :placeholder => "House status", :class => "form-control" %>
    </div>
    <% end %>
    
    <br>
    Image
    <%= f.file_field :picture %>
    <br>
    3D File
    <%= f.file_field :file %>
    <br>
    Meta File
    <%= f.file_field :meta %>
    <br>
    
    
    <%= f.submit "Create House", class: "btn btn-primary" %>

<% end %>

app/views/houses/show.html.erb
<h2><%= @house.name %></h2>

<div class="row">
  <div class="col-xs-6 col-md-3">
    <a href="<%= edit_house_path(@house.id) %>" class="thumbnail">
      <%= image_tag @house.picture %>
    </a>
    
  </div>
  
  
  <div class="col-md-5 col-md-offset-2">
      <h4>Available Options</h4>
      <hr>
      
      <ul>
          <% @options.each do |o| %>
              <li>
                  <%= link_to  o.name , option_path(o) %>
              </li>
          <% end %>
      </ul>
      
  </div>
  
</div>

<div class="row">
    
    <a href="<%= @house.file.to_s %>" download>
        <button type="button" class="btn btn-warning btn-lg">Download</button>
    </a>

    <%#= render "shared/exampleHouse" %>
    <%= link_to "/gameStarter/#{@house.id}" do %>
        <button type="button" class="btn btn-info btn-lg">View 3D House</button>
    <% end %>
    
    
    <%= link_to edit_house_path(@house.id) do %>
        <button type="button" class="btn btn-info btn-lg">Edit</button>
    <% end %>
    
    <%= link_to house_path(@house), method: "delete" do %>
        <button type="button" class="btn btn-danger btn-lg">Delete</button>
    <% end %>
    
    
    
</div>

<br>
<div class='jumbotron' id='house-info'>
                  
                  <div class="col-xs-6 col-sm-4">
                        <h3>About This House</h3>
                        
                        <dl>
                        <address>
                              <strong>Address</strong><br>
                              <%= @house.address %>                             
                        </address>
                        
                        <dt>Model Name</dt>
                        <dd><%= @house.name %> </dd>
                        <br>
                        <dt>Community</dt>
                        <dd>
                            <% if @house.community %>
                                <%= @house.community.name %>
                            <% else %>
                                [none selected]
                            <% end %>
                                
                        </dd>
                        <br>
                        <dt>Base Price</dt>
                        <dd>$254,000</dd>
                        </dl>
                        
                  </div>
                        
                  
                   <div class="col-xs-6 col-sm-4">
                        <h3>Specifications</h3>
                        <ul>
                        
                        <li>3 Bedrooms</li>   
                        <li>2 Bath</li>
                        <li>1,521 Finished Sq Ft</li>
                        <li>2,979 Total Sq Ft</li>
                        
                        </ul>
                  </div>
                  
                  
            </div>