config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  
  get 'signup'  => 'users#new' 
  resources :users
  
  get 'users' => 'users#index'
  get 'users/:id' => 'users#show'

  get 'create-house' => 'houses#new'
  get '/houses' => 'houses#index'
  resources :houses
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'
  
  get '/unreal' => 'webplayers#index'
  
  post '/' => 'sessions#create'
  
  get 'dashboard' => 'pages#dashboard'
  
  get 'index' => 'pages#index'
  get '/my-houses' => 'builder#houses'
  get '/my-customers' => 'builder#customers'
  get '/my-customers/:id' => 'builder#customer_info'
  get '/my-options' => 'builder#options'
  
  
  resources :options
  get 'all-users' => 'admin#users'
  get 'all-houses' => 'admin#houses'
  get 'all-options' => 'admin#options'
  
  get 'highscore' => 'unity#highscore'
  get 'highscoreUpdate' => 'unity#highscoreUpdate'
  get 'optionsJSON' => 'unity#optionsJSON'
  
  get 'houseName' => 'unity#houseName'
  get 'houseNameUpdate' => 'unity#houseNameUpdate'
  
  get 'game' => 'pages#game'
  get 'game/index.html' => 'pages#game'
  
  get 'username' => 'unity#username'
  
  get 'gameStarter/:id' => 'unity#gameStarter'
  get 'gameTester' => 'unity#gameTester'
  post 'updateChoices' => 'unity#updateChoices'
  
  get 'gameData' => 'unity#gameData'
  
  get 'communities' => 'builder#communities'
  post 'communities' => 'builder#createCommunity'
  get 'loginStats' => 'pages#loginStats'
  
  

end

app/views/pages/dashboard.html.erb
<h2>Dashboard</h2>
<hr>

<div class="row">
    <% if current_user && current_user.admin? %>
        <div class="col-md-4">
            
            <%= link_to all_users_path do %>
                <button type="button" class="btn btn-primary btn-lg btn-block">
                    <div class="col-md-1"> 
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                    </div>
                    All Users
                </button>
            <% end %>
            
            <br>
            
            <%= link_to all_houses_path do %>
                <button type="button" class="btn btn-primary btn-lg btn-block">
                    <div class="col-md-1"> 
                        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
                    </div>
                    All Houses
                </button>
            <% end %>
            
            <br>
            <%= link_to all_options_path do %>
                <button type="button" class="btn btn-primary btn-lg btn-block">
                    <div class="col-md-1"> 
                        <span class="glyphicon glyphicon-list" aria-hidden="true"></span>
                    </div>
                    Options
                </button>
            <% end %>
    </div>
    <% end %>
    
    
    
    
    <% if current_user && current_user.builder? %>
        <div class="col-md-4">
            
            <%= link_to  "/my-houses" do %>
                <button type="button" class="btn btn-primary btn-lg btn-block">
                    <div class="col-md-1"> 
                        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
                    </div>
                     My Houses
                </button>
            <% end %>
            
            <br>
            
            <%= link_to "/my-customers" do%>
                <button type="button" class="btn btn-primary btn-lg btn-block">
                    <div class="col-md-1"> 
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                    </div>
                    My Customers
                </button>
            <% end %>
            
            <br>
            <%= link_to communities_path do%>
                <button type="button" class="btn btn-primary btn-lg btn-block">
                    <div class="col-md-1"> 
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                    </div>
                    My Communities
                </button>
            <% end %>
            
        </div>
    <% end %>
    
    
    
    
    <% if current_user && current_user.buyer? %>
        <h1>Welcome, <%= current_user.first_name + " " + current_user.last_name %>!</h1>
        <h3>Your contractor: <%= current_user.contractor.first_name + " " + current_user.contractor.last_name %></h3>
        <p><a href="http://52.34.11.68/alpha/homes/testhouse4/index.html" class="btn btn-primary" role='button' onclick="window.open('http://52.34.11.68/alpha/homes/testhouse4/index.html', 'newwindow', 'width=1000, height=565'); return false;">Old 3D Viewer</a></p>
        
        <br>
        <%= link_to "/gameStarter/#{current_user.assigned_house.id.to_s}" do%>
            <button type="button" class="btn btn-primary">
                <div class="col-md-1"> 
                    <span class="glyphicon glyphicon-picture" aria-hidden="true"></span>
                </div>
                New 3D Viewer
            </button>
        <% end %>
        
        <%= link_to gameTester_path do%>
            <button type="button" class="btn btn-warning">
                <div class="col-md-1"> 
                    <span class="glyphicon glyphicon-picture" aria-hidden="true"></span>
                </div>
                TextBased Option Selector
            </button>
        <% end %>
        
     <% end %>
    

    
    
    
</div>

app/views/pages/game.html.erb
    <link rel="stylesheet" href="/unitywebbuild/TemplateData/style.css">
    <script src="/unitywebbuild/TemplateData/UnityProgress.js"></script>
    <p class="header"><span>Unity WebGL Player | </span>Ruby House</p>
    <div class="template-wrap clear">
      <canvas class="emscripten" id="canvas" oncontextmenu="event.preventDefault()" height="600px" width="960px" style="margin-top: 60px;"></canvas>

    </div>
    <p class="footer">&laquo; created with <a href="http://unity3d.com/" title="Go to unity3d.com">Unity</a> &raquo;</p>
    <script type='text/javascript'>
      var Module = {
        TOTAL_MEMORY: 268435456,
        errorhandler: null,			// arguments: err, url, line. This function must return 'true' if the error is handled, otherwise 'false'
        compatibilitycheck: null,
        dataUrl: "/unitywebbuild/Release/WebGL Builds.data",
        codeUrl: "/unitywebbuild/Release/WebGL Builds.js",
        memUrl: "/unitywebbuild/Release/WebGL Builds.mem",
      };
    </script>
    <script src="/unitywebbuild/Release/UnityLoader.js"></script>

app/views/pages/home.html.erb
   <div class="row">
       <br><br>
   </div>
    
    
    <div class="row" >
        <div class="col-md-8">
            <div class="jumbotron">
                <h1>EnvisionIt 360!</h1>
                <h3>
                    Welcome to our website. We are still under development, if you would like to know what we are all about, <a href="#">contact us here.</a>
                    If you have an account, go ahead and log in to the right.
                </h3>
            </div>
        </div>
    
        <div class="col-md-4">
            
        </div>
    </div>
    
    
    
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
        
      <%= form_for(:session, url: login_path) do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h2 class="modal-title" id="myModalLabel">Log In</h2>
      </div>
      
      <div class="modal-body">
          
        <div class="form-group">
            <%= f.email_field :email, :placeholder => "Email", :class => "form-control" %>
        </div>
            
        <div class="form-group">
            <%= f.password_field :password, :placeholder => "Password", :class => "form-control" %>
        </div>
        
      </div>
      
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit "Log in", class: 'btn btn-primary' %>
      </div>
      <% end %>
      
    </div>
  </div>
</div>

app/views/pages/loginStats.html.erb
LOGIN STATS

log

app/views/pages/my_customers.html.erb
<h2>My Customers</h2>
<hr>

app/views/pages/my_houses.html.erb
<h2>My Houses</h2>
<hr>

<%= render "shared/house_tiles" %>

<hr>
<p>
  <%= link_to new_house_path do %>
    <button type="button" class="btn btn-primary btn-lg">Add New Home</button>
  <% end %>
</p>

app/views/pages/show_customer.html.erb
<h2>Customer Details</h2>
<hr>