config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  
  get 'signup'  => 'users#new' 
  resources :users
  
  get 'users' => 'users#index'
  get 'users/:id' => 'users#show'

  get 'create-house' => 'houses#new'
  get '/houses' => 'houses#index'
  resources :houses
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'
  
  get '/unreal' => 'webplayers#index'
  
  post '/' => 'sessions#create'
  
  get 'dashboard' => 'pages#dashboard'
  
  get 'index' => 'pages#index'
  get '/my-houses' => 'builder#houses'
  get '/my-customers' => 'builder#customers'
  get '/my-customers/:id' => 'builder#customer_info'
  get '/my-options' => 'builder#options'
  
  
  resources :options
  get 'all-users' => 'admin#users'
  get 'all-houses' => 'admin#houses'
  get 'all-options' => 'admin#options'
  
  get 'highscore' => 'unity#highscore'
  get 'highscoreUpdate' => 'unity#highscoreUpdate'
  get 'optionsJSON' => 'unity#optionsJSON'
  
  get 'houseName' => 'unity#houseName'
  get 'houseNameUpdate' => 'unity#houseNameUpdate'
  
  get 'game' => 'pages#game'
  get 'game/index.html' => 'pages#game'
  
  get 'username' => 'unity#username'
  
  get 'gameStarter/:id' => 'unity#gameStarter'
  get 'gameTester' => 'unity#gameTester'
  post 'updateChoices' => 'unity#updateChoices'
  
  get 'gameData' => 'unity#gameData'
  
  get 'communities' => 'builder#communities'
  post 'communities' => 'builder#createCommunity'
  get 'loginStats' => 'pages#loginStats'
  
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EnvisionIt 360</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <%= favicon_link_tag 'favicon.ico' %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
   
      
</head>
<body <% if !current_user %>class="giant-image"<% end %>>
  
  <nav style="margin-top: 2px; background-color: #FFF">
    <ul class="nav nav-tabs">
      <li role="presentation"><a href="/"><b>EnvisionIt 360</b></a></li>
      
      <!--
      <li role="presentation"><a href="/users">Users</a></li>
      <li role="presentation"><a href="/houses">Houses</a></li>
      -->
      
      <% if current_user %>
      
      
            <% if current_user.builder? %>
            
              <li role="presentation"<% if request.path == my_houses_path %> class="active" <% end %>>
                <%= link_to "Houses", my_houses_path %>
              </li>
              <li role="presentation"<% if request.path == my_customers_path %> class="active" <% end %>>
                <%= link_to "Customers", my_customers_path %>
              </li>
              <li role="presentation"<% if request.path == my_options_path %> class="active" <% end %>>
                <%= link_to "Options", my_options_path %>
              </li>
              
            
            <% end %>  
            <% if current_user.admin? %>
              
              <li role="presentation"<% if request.path == all_users_path %> class="active" <% end %>>
                <%= link_to "Users", all_users_path %>
              </li>
              <li role="presentation"<% if request.path == all_houses_path %> class="active" <% end %>>
                <%= link_to "Houses", all_houses_path %>
              </li>
              <li role="presentation"<% if request.path == all_options_path %> class="active" <% end %>>
                <%= link_to "Options", all_options_path %>
              </li>
            
            <% end %>
            
            <li role="presentation" style="float: right"><%= link_to "Log out", logout_path, method: "delete" %></li>
            <li role="presentation" style="float: right"><a href="<%= user_path(current_user) %>"> <%= current_user.email %></a></li>
            
        <% else %>
          
          
          <li role="presentation" style="float: right"><a href="#" data-toggle="modal" data-target="#myModal"> Log In</a></li>
            
          
        <% end %>
        
        

    </ul>
  </nav>
  


  <div class="container">
    <%= yield %>
  </div>

</body>
</html>